version: 2

models:
  - name: fct_covid_cases
    columns:
      - name: date,
      - name: cases,
      - name: valid_from,
      - name: valid_to
  - name: all_data_by_date
    columns:
      - name: date,
      - name: cases,
      - name: deaths,
      - name: recovered
  - name: avg_covid_recovered_daily_metrics
    columns:
      - name: date,
      - name: recovered,
      - name: new_recovered,
      - name: avg_new_recovered_7d
  - name: avg_covid_deaths_daily_metrics
    columns:
      - name: date,
      - name: deaths,
      - name: new_deaths,
      - name: avg_new_deaths_7d
  - name: avg_covid_cases_daily_metrics
    columns:
      - name: date,
      - name: cases,
      - name: new_cases,
      - name: avg_new_cases_7d